<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$config['base_url'] = ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == "on") ? "https" : "http");
$config['base_url'] .= "://".$_SERVER['HTTP_HOST'];
$config['base_url'] .= str_replace(basename($_SERVER['SCRIPT_NAME']),"",$_SERVER['SCRIPT_NAME']); 
$config['index_page'] = '';
$config['uri_protocol']	= 'AUTO';
$config['url_suffix'] = '.html';
$config['language']	= 'english';
$config['charset'] = 'UTF-8';
$config['enable_hooks'] = TRUE;
$config['subclass_prefix'] = 'MY_';
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';
$config['allow_get_array']		= TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger']	= 'c';
$config['function_trigger']		= 'm';
$config['directory_trigger']	= 'd'; 
$config['log_threshold'] = 4;
$config['log_path'] = '';
$config['log_date_format'] = 'd-M-Y H:i:s';
$config['cache_path'] = '';
$config['encryption_key'] = 'MIIJRAIBADANBgkqhkiG9w0BAQEFAASCCS4wggkqAgEAAoICAQCs4hvT5V6LXEql';
$config['sess_cookie_name']		= 'hk_session';
$config['sess_expiration']		= 86400;
$config['sess_expire_on_close']	= FALSE;
$config['sess_encrypt_cookie']	= TRUE;
$config['sess_use_database']	= FALSE;
$config['sess_table_name']		= 'hk_sessions';
$config['sess_match_ip']		= FALSE;
$config['sess_match_useragent']	= FALSE;
$config['sess_time_to_update']	= 86400;
$config['cookie_prefix']	= "hk_";
$config['cookie_domain']	= "";
$config['cookie_path']		= "/";
$config['cookie_secure']	= FALSE;
$config['global_xss_filtering'] = TRUE;
$config['csrf_protection'] = TRUE;
$config['csrf_token_name'] = 'csrf_hk_token';
$config['csrf_cookie_name'] = 'csrf_hk_name';
$config['csrf_regenerate'] = TRUE;
$config['csrf_expire'] = 86400;
$config['compress_output'] = FALSE;
$config['time_reference'] = 'local';
$config['rewrite_short_tags'] = FALSE;
$config['proxy_ips'] = '';
$config['restore_key'] = 'hk@123';


//////////chỉnh sửa///////
$config['provide_service'] = '';
$config['secret_key'] = '';
$config['api_name'] = 'API-DOICARD-V1';
$config['username'] = '';
$config['password'] = '';
$config['auth'] = '';
$config['app_id'] = '';
$config['priv_key'] = '+==';
